# Generated by Django 5.2.3 on 2025-06-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('asal_sekolah', models.CharField(max_length=150)),
                ('skor', models.PositiveIntegerField()),
                ('screenshot', models.ImageField(upload_to='screenshots/')),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
